### ISSUE TITLE
Undefined method Monitor.isRunning()

### ISSUE THREAD

**Issue by felixbuenemann** [M6Web/websocket-bench#36]
The interrupt handler tries to call `bench.monitor.isRunning()` which isn't defined anywhere:

```
websocket-bench -t faye -a 3500 -c 50 ws://localhost:3100/faye
Launch bench with 3500 total connection, 50 concurent connection
0 message(s) send by client
1 worker(s)
WS server : faye
^C
Gracefully stoping worker from SIGINT (Ctrl+C)
/usr/local/lib/node_modules/websocket-bench/index.js:102
    if (bench.monitor.isRunning()) {
                      ^
TypeError: undefined is not a function
    at null._onTimeout (/usr/local/lib/node_modules/websocket-bench/index.js:102:23)
    at Timer.listOnTimeout (timers.js:119:15)
```

**Comment by mkozjak** [comment]
+1. Is this repo maintained?

```
Gracefully stoping worker from SIGINT (Ctrl+C)
/usr/lib/node_modules/websocket-bench/index.js:102
    if (bench.monitor.isRunning()) {
                      ^

TypeError: bench.monitor.isRunning is not a function
    at null._onTimeout (/usr/lib/node_modules/websocket-bench/index.js:102:23)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by kennydee** [comment]
@mkozjak Not really.

We don't use it anymore :/
