### ISSUE TITLE
npm install failure 

### ISSUE THREAD

**Issue by yowenter** [M6Web/websocket-bench#49]
Hi,  I've tried install websocket-bench use npm. 
I've got some errors ,it seems that the reason is 
`http fetch 404 http://github.com/component/emitter/archive/1.0.1.tar.gz` .

```
 npm WARN deprecated extendable@0.0.6: This project has been renamed to extendible. This project will not receive any updates anymore
npm ERR! fetch failed http://github.com/component/emitter/archive/1.0.1.tar.gz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.11.3"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.11.3"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.11.3"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.11.3"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.11.3"})
npm ERR! fetch failed http://github.com/component/emitter/archive/1.0.1.tar.gz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404

> bufferutil@1.2.1 install /usr/local/lib/node_modules/websocket-bench/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9

> utf-8-validate@1.2.1 install /usr/local/lib/node_modules/websocket-bench/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9

> utf-8-validate@1.2.1 install /usr/local/lib/node_modules/websocket-bench/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9

> bufferutil@1.2.1 install /usr/local/lib/node_modules/websocket-bench/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
npm ERR! fetch failed http://github.com/component/emitter/archive/1.0.1.tar.gz
npm ERR! Darwin 15.6.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "websocket-bench"
npm ERR! node v0.12.2
npm ERR! npm  v2.11.3

npm ERR! fetch failed with status code 404
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wenter/npm-debug.log

```

The debug log :

```

9272 info attempt registry request try #1 at 17:12:32
9273 http fetch GET http://github.com/component/emitter/archive/1.0.1.tar.gz
9274 http fetch 404 http://github.com/component/emitter/archive/1.0.1.tar.gz
9275 error fetch failed http://github.com/component/emitter/archive/1.0.1.tar.gz
9276 verbose about to build /usr/local/lib/node_modules/websocket-bench/node_modules/engine.io-client
9277 verbose unlock done using /Users/wenter/.npm/_locks/engine-io-client-66ea7499c19d7102.lock for /usr/local/lib/node_modules/websocket-bench/node_modules/engine.io-client
9278 verbose about to build /usr/local/lib/node_modules/websocket-bench
9279 verbose unlock done using /Users/wenter/.npm/_locks/websocket-bench-f4b68275b6acba70.lock for /usr/local/lib/node_modules/websocket-bench
9280 verbose stack Error: fetch failed with status code 404
9280 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/fetch.js:51:14)
9280 verbose stack     at Request.emit (events.js:107:17)
9280 verbose stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1142:10)
9280 verbose stack     at ClientRequest.emit (events.js:107:17)
9280 verbose stack     at HTTPParser.parserOnIncomingClient (_http_client.js:426:21)
9280 verbose stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
9280 verbose stack     at Socket.socketOnData (_http_client.js:317:20)
9280 verbose stack     at Socket.emit (events.js:107:17)
9280 verbose stack     at readableAddChunk (_stream_readable.js:163:16)
9280 verbose stack     at Socket.Readable.push (_stream_readable.js:126:10)
9281 verbose cwd /Users/wenter
9282 error Darwin 15.6.0
9283 error argv "node" "/usr/local/bin/npm" "install" "-g" "websocket-bench"
9284 error node v0.12.2
9285 error npm  v2.11.3
9286 error fetch failed with status code 404
9287 error If you need help, you may report this error at:
9287 error     <https://github.com/npm/npm/issues>
9288 verbose exit [ 1, true ]
```

much thanks .

**Comment by muxi166** [comment]
npm install failed too

gyp ERR! stack     at C:\Users\kachesiji\AppData\Roaming\npm\node_modules\cnpm\n
ode_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kachesiji\\Ap
pData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin\
\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\kachesiji\git\websocket-bench\node_modules\_utf-8-validate
@1.2.2@utf-8-validate
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
[utf-8-validate@1.2.x] optional install error: Error: Run "C:\Windows\system32\c
md.exe /d /s /c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\kachesiji\AppData\Roaming\npm\node_mo
dules\cnpm\node_modules\runscript\index.js:74:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by yxzyxzyxz** [comment]
我也失败了。。
