### ISSUE TITLE
socket.io transport error

### ISSUE THREAD

**Issue by balaphp** [M6Web/websocket-bench#6]
command i have used:  websocket-bench -a 100000 -c 10000 -w 4  {url} 
/usr/local/lib/node_modules/websocket-bench/node_modules/socket.io-client/lib/socket.js:281
      self.transport.onClose();
                     ^
TypeError: Cannot call method 'onClose' of null
    at null._onTimeout (/usr/local/lib/node_modules/websocket-bench/node_modules/socket.io-client/lib/socket.js:281:22)
    at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

/usr/local/lib/node_modules/websocket-bench/node_modules/socket.io-client/lib/socket.js:281
      self.transport.onClose();
                     ^
TypeError: Cannot call method 'onClose' of null
    at null._onTimeout (/usr/local/lib/node_modules/websocket-bench/node_modules/socket.io-client/lib/socket.js:281:22)
    at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

**Comment by thanhson1085** [comment]
+1

**Comment by hequanb** [comment]
hello, what's situation in using argument `-w <n>` ,
